### ISSUE TITLE
Links in markup hard to see

### ISSUE THREAD

**Issue by iamdoubz** [iamdoubz/Gitea-Pitch-Black#2]
Please fix using this code:

```css
.markup a, .ui.breadcrumb a {
    color: var(--color-primary-light-7);
    cursor: pointer;
    text-decoration: none;
    border-bottom: 1px solid var(--color-primary);
    transition-property: all
}

.markup a:hover, .ui.breadcrumb a:hover {
    color: #000;
    cursor: pointer;
    text-decoration: none;
    background: #fff;
    background-color: #fff
}

.markup .anchor {
    border-bottom: none
}

.markup .anchor:hover {
    color: var(--color-primary-light-7);
    border-bottom: none;
    background: var(--color-body);
    background-color: var(--color-body)
}
```
