### ISSUE TITLE
Can only see the line you are editing

### ISSUE THREAD

**Issue by iamdoubz** [iamdoubz/Gitea-Pitch-Black#4]
When editing a specific file, you cannot see any other lines besides the one you are currently in. [Original link](https://git.dou.bet/iamdoubz/Gitea-Pitch-Black/issues/2).

![image](https://user-images.githubusercontent.com/4871781/151434747-e8f842ee-bc2f-46c8-9912-e5e25fcac4ec.png)

**Comment by iamdoubz** [comment]
Quick fix:

```css
.mtk1 {
    color: #6D7178!important;
}
```
