### ISSUE TITLE
Incompatible with top navbar on 1.20

### ISSUE THREAD

**Issue by HurricanKai** [iamdoubz/Gitea-Pitch-Black#9]
I've just installed this into my otherwise standard gitea installation version 1.20.2

The top navbar shows up entirely white. going to /expore shows the explore button in black, but everything else is still white.

I'm not sure how the theming works, so I failed fixing it myself. I'd appreciate any advice / fix!

**Comment by nicorac** [comment]
Just created a [PR](https://github.com/iamdoubz/Gitea-Pitch-Black/pull/10) for this.

Meanwhile, on Gitea 1.20 you can fix it manually by editing `theme-pitchblack.css`.
Add new color definitions at the end of `:root` element variable declarations (about line 203):

```css
  --color-editor-line-highlight: var(--color-primary-light-5);
  --color-project-board-bg: var(--color-secondary-light-2);
  /* patch start */
  --color-nav-bg: var(--color-body);        
  --color-nav-hover-bg: var(--color-hover);
  /* patch end */
}

::-webkit-calendar-picker-indicator {
  filter: invert(.8);
}
```
